---
title: "Table 2 - Heritability Calculations"
author: "Tyler L Foster"
output: html_document
date: "2024-04-04"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if (!require("lme4")) install.packages("lme4")
library(lme4)

if (!require("scales")) install.packages("scales")
library(scales)

if (!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

if (!require("dplyr")) install.packages("dplyr")
library(dplyr)

if (!require("janitor")) install.packages("janitor")
library(janitor)

if (!require("data.table")) install.packages("data.table")
library(data.table)

if (!require("stringr")) install.packages("stringr")
library(stringr)

if (!require("ggpubr")) install.packages("ggpubr")
library(ggpubr)

if (!require("RColorBrewer")) install.packages("RColorBrewer")
library(RColorBrewer)

if (!require("ggrepel")) install.packages("ggrepel")
library(ggrepel)

if (!require("readxl")) install.packages("readxl")
library(readxl)

if (!require("lme4")) install.packages("lme4")
library(lme4)

if (!require("ggResidpanel")) install.packages("ggResidpanel")
library(ggResidpanel)

if (!require("boot")) install.packages("boot")
library(boot)

if (!require("emmeans")) install.packages("emmeans")
library(emmeans)
```

```{r}
#Read in excel files
P.1 <- read_excel("Raw_Scores_1-5.xlsx", sheet = "Pollen")
P.1

P.2 <- read_excel("Raw_Scores_2-5.xlsx", sheet = "Pollen")
P.2

A.1 <- read_excel("Raw_Scores_1-5.xlsx", sheet = "Anther")
A.1

A.2 <- read_excel("Raw_Scores_2-5.xlsx", sheet = "Anther")
A.2
```

```{r}
#Change from character to factor variable
P.1$Environment <- as.factor(P.1$Environment)
P.1$Group <- as.factor(P.1$Group)

P.2$Environment <- as.factor(P.2$Environment)
P.2$Group <- as.factor(P.2$Group)

A.1$Environment <- as.factor(A.1$Environment)
A.1$Group <- as.factor(A.1$Group)

A.2$Environment <- as.factor(A.2$Environment)
A.2$Group <- as.factor(A.2$Group)
```

```{r}
#Logit transformation of phenotype
P.1$logit <- logit(P.1$HMF_plus_0.005)
P.2$logit <- logit(P.2$HMF_plus_0.005)
A.1$logit <- logit(A.1$HMF_plus_0.005)
A.2$logit <- logit(A.2$HMF_plus_0.005)
```

```{r}
#Harmonic Mean of Environment
1/mean(1/table(P.1$Group))
1/mean(1/table(P.2$Group))
1/mean(1/table(A.1$Group))
1/mean(1/table(A.2$Group))
```

```{r}
#Filtering out the parental inbreds for calculating heritability of only the recombinant groups
P.1_recombinants <- P.1 %>% filter(!Group %in% c("A427", "Wf9"))
P.2_recombinants <- P.2 %>% filter(!Group %in% c("A427", "Wf9"))
A.1_recombinants <- A.1 %>% filter(!Group %in% c("A427", "Wf9"))
A.2_recombinants <- A.2 %>% filter(!Group %in% c("A427", "Wf9"))
```

# Linear Models (random effects) for trait/score combinations for calculating heritability

```{r}
linear_pollen1.r <-lmer(logit ~ (1|Environment) + (1|Group), data = P.1_recombinants)
```

```{r}
linear_pollen2.r <-lmer(logit ~ (1|Environment) + (1|Group), data = P.2_recombinants)
```

```{r}
linear_anther1.r <-lmer(logit ~ (1|Environment) + (1|Group), data = A.1_recombinants)
```

```{r}
linear_anther2.r <-lmer(logit ~ (1|Environment) + (1|Group), data = A.2_recombinants)
```

# Heritability Calculations

```{r}
summary(linear_pollen1.r)
```

```{r}
# PSC HMF Scores 1-5
gen_var_p1 = 1.465
res_var_p1 = 1.017
gen_var_p1/(gen_var_p1 + (res_var_p1/2.88))
```

```{r}
summary(linear_pollen2.r)
```

```{r}
# PSC HMF Scores 2-5
gen_var_p2 = 2.1358
res_var_p2 = 0.9485
gen_var_p2/(gen_var_p2 + (res_var_p2/2.88))
```

```{r}
summary(linear_anther1.r)
```

```{r}
# FAE HMF Scores 1-5
gen_var_a1 = 0.7210
res_var_a1 = 0.9814
gen_var_a1/(gen_var_a1 + (res_var_a1/2.88))
```

```{r}
summary(linear_anther2.r)
```

```{r}
# FAE HMF Scores 2-5
gen_var_a2 = 2.01732
res_var_a2 = 0.83385
gen_var_a2/(gen_var_a2 + (res_var_a2/2.88))
```